"""initial schema

Revision ID: 0fc208134b8a
Revises: 
Create Date: 2026-08-18 21:00:07.920101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc208134b8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='学校名称'),
    sa.Column('url', sa.String(length=500), nullable=False, comment='学校官网URL'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('config', sa.Text(), nullable=True, comment='爬取配置JSON'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='部门名称'),
    sa.Column('list_url', sa.String(length=1000), nullable=True, comment='通知列表页URL'),
    sa.Column('list_selector', sa.String(length=500), nullable=True, comment='列表项CSS选择器'),
    sa.Column('title_selector', sa.String(length=500), nullable=True, comment='标题CSS选择器'),
    sa.Column('link_selector', sa.String(length=500), nullable=True, comment='链接CSS选择器'),
    sa.Column('date_selector', sa.String(length=500), nullable=True, comment='日期CSS选择器'),
    sa.Column('content_selector', sa.String(length=500), nullable=True, comment='正文内容CSS选择器'),
    sa.Column('group_name', sa.String(length=200), nullable=True, comment='导航分组名称（如院系设置、科学研究）'),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True, comment='上次完整抓取完成时间（用于增量抓取）'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('new_count', sa.Integer(), nullable=True, comment='新增数量'),
    sa.Column('total_count', sa.Integer(), nullable=True, comment='检查总数'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='running/success/failed'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='标题'),
    sa.Column('url', sa.String(length=2000), nullable=True, comment='原文链接'),
    sa.Column('content_html', sa.Text(), nullable=True, comment='正文HTML'),
    sa.Column('content_text', sa.Text(), nullable=True, comment='正文纯文本'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI摘要'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='内容哈希（用于变更检测）'),
    sa.Column('is_read', sa.Boolean(), nullable=True, comment='是否已读'),
    sa.Column('is_updated', sa.Boolean(), nullable=True, comment='是否被更新过'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index('idx_announcement_hash', ['content_hash'], unique=False)
        batch_op.create_index('idx_announcement_published', ['published_at'], unique=False)
        batch_op.create_index('idx_announcement_school_dept', ['school_id', 'department_id'], unique=False)
        batch_op.create_index('idx_announcement_url', ['url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index('idx_announcement_url')
        batch_op.drop_index('idx_announcement_school_dept')
        batch_op.drop_index('idx_announcement_published')
        batch_op.drop_index('idx_announcement_hash')

    op.drop_table('announcements')
    op.drop_table('scrape_logs')
    op.drop_table('departments')
    op.drop_table('schools')
    op.drop_table('app_config')
    # ### end Alembic commands ###
