"""multi-user: users/subscriptions/user_reads/rate_buckets + school subscription fields

Revision ID: 6bdcafbca9e7
Revises: 0fc208134b8a
Create Date: 2026-08-30 03:56:27.576439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdcafbca9e7'
down_revision = '0fc208134b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_buckets',
    sa.Column('key', sa.String(length=150), nullable=False, comment='login:ip / login:user / register:ip / submit:user 等'),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False, comment='admin/user'),
    sa.Column('security_question', sa.String(length=200), nullable=True, comment='密保问题'),
    sa.Column('security_answer_hash', sa.String(length=64), nullable=True, comment='密保答案哈希'),
    sa.Column('recovery_attempts', sa.Integer(), nullable=True, comment='找回尝试计数'),
    sa.Column('recovery_locked_until', sa.DateTime(), nullable=True, comment='找回锁定截止时间'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'school_id', name='uq_subscription_user_school')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('idx_subscriptions_school', ['school_id'], unique=False)

    op.create_table('user_reads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'announcement_id', name='uq_user_read')
    )
    with op.batch_alter_table('user_reads', schema=None) as batch_op:
        batch_op.create_index('idx_user_reads_user', ['user_id'], unique=False)

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_by', sa.Integer(), nullable=True, comment='提交人（存量学校为 NULL）'))
        batch_op.add_column(sa.Column('subscriber_count', sa.Integer(), server_default='0', nullable=False, comment='订阅人数缓存（订阅事务内算术维护）'))
        batch_op.create_foreign_key('fk_schools_submitted_by', 'users',
                                    ['submitted_by'], ['id'])

    # ---- 存量数据映射（手编）：单管理员 → admin 账户，抓取不中断 ----
    import secrets as _secrets
    from datetime import datetime as _dt, timezone as _tz
    from werkzeug.security import generate_password_hash as _gph

    bind = op.get_bind()
    now = _dt.now(_tz.utc)
    # 1) 现全局密码 → admin 哈希账户（密码为空时随机生成）
    pw = bind.execute(sa.text(
        "SELECT value FROM app_config WHERE key='app_password'")).scalar()
    bind.execute(sa.text(
        "INSERT INTO users (username, password_hash, role, created_at) "
        "VALUES ('admin', :h, 'admin', :now)"),
        {'h': _gph(pw or _secrets.token_hex(12)), 'now': now})
    uid = bind.execute(sa.text(
        "SELECT id FROM users WHERE username='admin'")).scalar()
    # 2) admin 自动订阅全部存量学校 → 订阅驱动下抓取不中断
    bind.execute(sa.text(
        "INSERT INTO subscriptions (user_id, school_id, created_at) "
        "SELECT :uid, id, :now FROM schools"), {'uid': uid, 'now': now})
    bind.execute(sa.text("UPDATE schools SET subscriber_count=1"))
    # 3) 存量 is_read=1 → admin 的已读记录
    bind.execute(sa.text(
        "INSERT INTO user_reads (user_id, announcement_id, read_at) "
        "SELECT :uid, id, COALESCE(created_at, :now) FROM announcements "
        "WHERE is_read IS TRUE"), {'uid': uid, 'now': now})
    # 4) 全局密保迁入 admin 账户；app_password 键保留作回滚兜底，不删
    q = bind.execute(sa.text(
        "SELECT value FROM app_config WHERE key='security_question'")).scalar()
    ah = bind.execute(sa.text(
        "SELECT value FROM app_config WHERE key='security_answer_hash'")).scalar()
    if q:
        bind.execute(sa.text(
            "UPDATE users SET security_question=:q, security_answer_hash=:ah "
            "WHERE id=:uid"), {'q': q, 'ah': ah, 'uid': uid})
    bind.execute(sa.text(
        "DELETE FROM app_config WHERE key IN "
        "('recovery_attempts','recovery_last_attempt')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite batch 重建表时，随 submitted_by 列移除自动丢弃其外键
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('subscriber_count')
        batch_op.drop_column('submitted_by')

    with op.batch_alter_table('user_reads', schema=None) as batch_op:
        batch_op.drop_index('idx_user_reads_user')

    op.drop_table('user_reads')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_subscriptions_school')

    op.drop_table('subscriptions')
    op.drop_table('users')
    op.drop_table('rate_buckets')
    # ### end Alembic commands ###
