"""Verify or restore the exact, self-hosted font distribution in fonts/manifest.json.

    python scripts/assets/vendor_fonts.py --verify
    python scripts/assets/vendor_fonts.py --restore

Normal verification is offline. Restore downloads only pinned Google-hosted font
assets and their licenses, checks SHA-256 before writing, and regenerates fonts.css.
It never discovers newer upstream versions or builds a sample-text-only subset.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[2]
STATIC = ROOT / "frontend" / "static"
MANIFEST = STATIC / "fonts" / "manifest.json"
ALLOWED_HOSTS = {"fonts.googleapis.com", "fonts.gstatic.com", "raw.githubusercontent.com", "cdn.jsdelivr.net"}


def digest(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def asset_path(relative: str) -> Path:
    path = (STATIC / relative).resolve()
    if not path.is_relative_to(STATIC.resolve()) or not relative.startswith("fonts/"):
        raise ValueError(f"Unexpected asset path: {relative}")
    return path


def render_css(manifest: dict) -> str:
    blocks = ["/* Generated by scripts/assets/vendor_fonts.py from fonts/manifest.json. */"]
    for family in manifest["families"]:
        blocks.append(f"/* {family['name']}: {family['distribution_revision']}; SIL OFL 1.1. */")
        for face in family["faces"]:
            blocks.append("\n".join([
                "@font-face {",
                f"  font-family: '{family['name']}';",
                "  font-style: normal;",
                "  font-weight: 400 700;",
                "  font-display: swap;",
                f"  src: url('../{face['path']}') format('woff2');",
                f"  unicode-range: {face['unicode_range']};",
                "}",
            ]))
    return "\n".join(blocks) + "\n"


def verify(manifest: dict) -> list[str]:
    problems = []
    for entry in manifest["files"]:
        path = asset_path(entry["path"])
        if not path.is_file() or digest(path.read_bytes()) != entry["sha256"]:
            problems.append(entry["path"])
    css = STATIC / "css" / "fonts.css"
    if not css.is_file() or css.read_text(encoding="utf-8") != render_css(manifest):
        problems.append("css/fonts.css (generated declarations)")
    return problems



def parse_unicode_ranges(value: str) -> set[int]:
    codepoints = set()
    for part in value.split(","):
        bounds = part.strip().removeprefix("U+").removeprefix("u+").split("-")
        first, last = int(bounds[0], 16), int(bounds[-1], 16)
        codepoints.update(range(first, last + 1))
    return codepoints


def build_supplement(source: Path, unicode_range: str, output: Path) -> None:
    """Subset only missing upstream cmap entries; preserve the variable font."""
    from fontTools import subset
    from fontTools.ttLib import TTFont

    options = subset.Options()
    options.name_IDs = ["*"]
    options.name_languages = ["*"]
    options.recalc_timestamp = False
    options.recommended_glyphs = True
    font = TTFont(source, recalcTimestamp=False)
    try:
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=parse_unicode_ranges(unicode_range))
        subsetter.subset(font)
        font.flavor = "woff2"
        font.save(output, reorderTables=True)
    finally:
        font.close()


def restore_supplements(manifest: dict, entries: list[dict]) -> None:
    if not entries:
        return
    from importlib.metadata import PackageNotFoundError, version
    import requests

    expected = manifest["supplement_build"]["packages"]
    for package, required in expected.items():
        try:
            actual = version(package)
        except PackageNotFoundError:
            actual = "missing"
        if actual != required:
            command = " ".join(f"{name}=={ver}" for name, ver in expected.items())
            raise RuntimeError(f"Rebuilding font supplements requires: pip install {command}")
    source = manifest["supplement_build"]["source"]
    with tempfile.TemporaryDirectory(prefix="school-watcher-font-build-") as scratch:
        original = Path(scratch) / "upstream.ttf"
        failures = []
        for url in source["urls"]:
            if urlparse(url).scheme != "https" or urlparse(url).hostname not in ALLOWED_HOSTS:
                raise ValueError("Untrusted supplemental font source")
            try:
                response = requests.get(url, timeout=(10, 45))
                response.raise_for_status()
                if digest(response.content) != source["sha256"]:
                    raise ValueError("Font source SHA-256 changed")
                original.write_bytes(response.content)
                break
            except (requests.RequestException, ValueError) as exc:
                failures.append(str(exc))
        else:
            raise RuntimeError("Cannot restore the pinned font source: " + "; ".join(failures))
        for entry in entries:
            output = Path(scratch) / "supplement.woff2"
            build_supplement(original, entry["unicode_range"], output)
            content = output.read_bytes()
            if digest(content) != entry["sha256"]:
                raise ValueError(f"Supplement rebuild differs: {entry['path']}")
            target = asset_path(entry["path"])
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(content)


def restore(manifest: dict) -> None:
    import requests

    def download(entry: dict) -> None:
        path = asset_path(entry["path"])
        if path.is_file() and digest(path.read_bytes()) == entry["sha256"]:
            return
        url = entry["url"]
        if urlparse(url).scheme != "https" or urlparse(url).hostname not in ALLOWED_HOSTS:
            raise ValueError(f"Untrusted font host for {entry['path']}")
        response = requests.get(url, headers=manifest["request_headers"], timeout=(15, 45))
        response.raise_for_status()
        if digest(response.content) != entry["sha256"]:
            raise ValueError(f"Upstream bytes changed; refusing {entry['path']}")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(response.content)

    remote = [entry for entry in manifest["files"] if entry["kind"] != "generated-font"]
    generated = [entry for entry in manifest["files"] if entry["kind"] == "generated-font"
                 and (not asset_path(entry["path"]).is_file()
                      or digest(asset_path(entry["path"]).read_bytes()) != entry["sha256"])]
    with ThreadPoolExecutor(max_workers=8) as executor:
        list(executor.map(download, remote))
    restore_supplements(manifest, generated)
    (STATIC / "css" / "fonts.css").write_text(render_css(manifest), encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument("--verify", action="store_true", help="Offline integrity check (default)")
    modes.add_argument("--restore", action="store_true", help="Restore pinned assets; requires network")
    args = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if args.restore:
        restore(manifest)
    problems = verify(manifest)
    if problems:
        print("Font integrity check failed:\n" + "\n".join(problems))
        return 1
    print(f"Verified {len(manifest['files'])} pinned font/source/license assets and local CSS.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
